version: "3.7"

services:
  frontend:
    container_name: litefarm-web
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
  backend:
    container_name: litefarm-api
    image: nginx:1.15
    # ports:
    #   - "5000:5000"
    volumes:
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
